a=input("enter the fisrt name")
b=input("enter the sec name")
c=input("enter the third name")
d=input("enter the fourth name")
e=input("enter the fifth name")
l=(a,b,c,d,e)
print(l)
l.sort()
print(l)